export const COUNTRIES = [
  { id: "Afghanistan", value: "Afghanistan" },
  { id: "Albania", value: "Albania" },
  { id: "Algeria", value: "Algeria" },
  { id: "Andorra", value: "Andorra" },
  { id: "Angola", value: "Angola" },
  { id: "Antigua and Barbuda", value: "Antigua and Barbuda" },
  { id: "Argentina", value: "Argentina" },
  { id: "Armenia", value: "Armenia" },
  { id: "Australia", value: "Australia" },
  { id: "Austria", value: "Austria" },
  { id: "Azerbaijan", value: "Azerbaijan" },
  { id: "Bahamas", value: "Bahamas" },
  { id: "Bahrain", value: "Bahrain" },
  { id: "Bangladesh", value: "Bangladesh" },
  { id: "Barbados", value: "Barbados" },
  { id: "Belarus", value: "Belarus" },
  { id: "Belgium", value: "Belgium" },
  { id: "Belize", value: "Belize" },
  { id: "Benin", value: "Benin" },
  { id: "Bhutan", value: "Bhutan" },
  { id: "Bolivia", value: "Bolivia" },
  { id: "Bosnia and Herzegovina", value: "Bosnia and Herzegovina" },
  { id: "Botswana", value: "Botswana" },
  { id: "Brazil", value: "Brazil" },
  { id: "Brunei", value: "Brunei" },
  { id: "Bulgaria", value: "Bulgaria" },
  { id: "Burkina Faso", value: "Burkina Faso" },
  { id: "Burundi", value: "Burundi" },
  { id: "Cabo Verde", value: "Cabo Verde" },
  { id: "Cambodia", value: "Cambodia" },
  { id: "Cameroon", value: "Cameroon" },
  { id: "Canada", value: "Canada" },
  { id: "Central African Republic", value: "Central African Republic" },
  { id: "Chad", value: "Chad" },
  { id: "Chile", value: "Chile" },
  { id: "China", value: "China" },
  { id: "Colombia", value: "Colombia" },
  { id: "Comoros", value: "Comoros" },
  { id: "Congo (Congo-Brazzaville)", value: "Congo (Congo-Brazzaville)" },
  {
    id: "Congo (Democratic Republic) (Congo-Kinshasa)",
    value: "Congo (Democratic Republic) (Congo-Kinshasa)",
  },
  { id: "Costa Rica", value: "Costa Rica" },
  { id: "Croatia", value: "Croatia" },
  { id: "Cuba", value: "Cuba" },
  { id: "Cyprus", value: "Cyprus" },
  { id: "Czech Republic", value: "Czech Republic" },
  { id: "Denmark", value: "Denmark" },
  { id: "Djibouti", value: "Djibouti" },
  { id: "Dominica", value: "Dominica" },
  { id: "Dominican Republic", value: "Dominican Republic" },
  { id: "Ecuador", value: "Ecuador" },
  { id: "Egypt", value: "Egypt" },
  { id: "El Salvador", value: "El Salvador" },
  { id: "Equatorial Guinea", value: "Equatorial Guinea" },
  { id: "Eritrea", value: "Eritrea" },
  { id: "Estonia", value: "Estonia" },
  { id: "Eswatini", value: "Eswatini" },
  { id: "Ethiopia", value: "Ethiopia" },
  { id: "Fiji", value: "Fiji" },
  { id: "Finland", value: "Finland" },
  { id: "France", value: "France" },
  { id: "Gabon", value: "Gabon" },
  { id: "Gambia", value: "Gambia" },
  { id: "Georgia", value: "Georgia" },
  { id: "Germany", value: "Germany" },
  { id: "Ghana", value: "Ghana" },
  { id: "Greece", value: "Greece" },
  { id: "Grenada", value: "Grenada" },
  { id: "Guatemala", value: "Guatemala" },
  { id: "Guinea", value: "Guinea" },
  { id: "Guinea-Bissau", value: "Guinea-Bissau" },
  { id: "Guyana", value: "Guyana" },
  { id: "Haiti", value: "Haiti" },
  { id: "Honduras", value: "Honduras" },
  { id: "Hungary", value: "Hungary" },
  { id: "Iceland", value: "Iceland" },
  { id: "India", value: "India" },
  { id: "Indonesia", value: "Indonesia" },
  { id: "Iran", value: "Iran" },
  { id: "Iraq", value: "Iraq" },
  { id: "Ireland", value: "Ireland" },
  { id: "Israel", value: "Israel" },
  { id: "Italy", value: "Italy" },
  { id: "Jamaica", value: "Jamaica" },
  { id: "Japan", value: "Japan" },
  { id: "Jordan", value: "Jordan" },
  { id: "Kazakhstan", value: "Kazakhstan" },
  { id: "Kenya", value: "Kenya" },
  { id: "Kiribati", value: "Kiribati" },
  { id: "Korea (North)", value: "Korea (North)" },
  { id: "Korea (South)", value: "Korea (South)" },
  { id: "Kuwait", value: "Kuwait" },
  { id: "Kyrgyzstan", value: "Kyrgyzstan" },
  { id: "Laos", value: "Laos" },
  { id: "Latvia", value: "Latvia" },
  { id: "Lebanon", value: "Lebanon" },
  { id: "Lesotho", value: "Lesotho" },
  { id: "Liberia", value: "Liberia" },
  { id: "Libya", value: "Libya" },
  { id: "Liechtenstein", value: "Liechtenstein" },
  { id: "Lithuania", value: "Lithuania" },
  { id: "Luxembourg", value: "Luxembourg" },
  { id: "Madagascar", value: "Madagascar" },
  { id: "Malawi", value: "Malawi" },
  { id: "Malaysia", value: "Malaysia" },
  { id: "Maldives", value: "Maldives" },
  { id: "Mali", value: "Mali" },
  { id: "Malta", value: "Malta" },
  { id: "Marshall Islands", value: "Marshall Islands" },
  { id: "Mauritania", value: "Mauritania" },
  { id: "Mauritius", value: "Mauritius" },
  { id: "Mexico", value: "Mexico" },
  { id: "Micronesia", value: "Micronesia" },
  { id: "Moldova", value: "Moldova" },
  { id: "Monaco", value: "Monaco" },
  { id: "Mongolia", value: "Mongolia" },
  { id: "Montenegro", value: "Montenegro" },
  { id: "Morocco", value: "Morocco" },
  { id: "Mozambique", value: "Mozambique" },
  { id: "Myanmar (formerly Burma)", value: "Myanmar (formerly Burma)" },
  { id: "Namibia", value: "Namibia" },
  { id: "Nauru", value: "Nauru" },
  { id: "Nepal", value: "Nepal" },
  { id: "Netherlands", value: "Netherlands" },
  { id: "New Zealand", value: "New Zealand" },
  { id: "Nicaragua", value: "Nicaragua" },
  { id: "Niger", value: "Niger" },
  { id: "Nigeria", value: "Nigeria" },
  { id: "North Macedonia", value: "North Macedonia" },
  { id: "Norway", value: "Norway" },
  { id: "Oman", value: "Oman" },
  { id: "Pakistan", value: "Pakistan" },
  { id: "Palau", value: "Palau" },
  { id: "Panama", value: "Panama" },
  { id: "Papua New Guinea", value: "Papua New Guinea" },
  { id: "Paraguay", value: "Paraguay" },
  { id: "Peru", value: "Peru" },
  { id: "Philippines", value: "Philippines" },
  { id: "Poland", value: "Poland" },
  { id: "Portugal", value: "Portugal" },
  { id: "Qatar", value: "Qatar" },
  { id: "Romania", value: "Romania" },
  { id: "Russia", value: "Russia" },
  { id: "Rwanda", value: "Rwanda" },
  { id: "Saint Kitts and Nevis", value: "Saint Kitts and Nevis" },
  { id: "Saint Lucia", value: "Saint Lucia" },
  {
    id: "Saint Vincent and the Grenadines",
    value: "Saint Vincent and the Grenadines",
  },
  { id: "Samoa", value: "Samoa" },
  { id: "San Marino", value: "San Marino" },
  { id: "Sao Tome and Principe", value: "Sao Tome and Principe" },
  { id: "Saudi Arabia", value: "Saudi Arabia" },
  { id: "Senegal", value: "Senegal" },
  { id: "Serbia", value: "Serbia" },
  { id: "Seychelles", value: "Seychelles" },
  { id: "Sierra Leone", value: "Sierra Leone" },
  { id: "Singapore", value: "Singapore" },
  { id: "Slovakia", value: "Slovakia" },
  { id: "Slovenia", value: "Slovenia" },
  { id: "Solomon Islands", value: "Solomon Islands" },
  { id: "Somalia", value: "Somalia" },
  { id: "South Africa", value: "South Africa" },
  { id: "South Sudan", value: "South Sudan" },
  { id: "Spain", value: "Spain" },
  { id: "Sri Lanka", value: "Sri Lanka" },
  { id: "Sudan", value: "Sudan" },
  { id: "Suriname", value: "Suriname" },
  { id: "Sweden", value: "Sweden" },
  { id: "Switzerland", value: "Switzerland" },
  { id: "Syria", value: "Syria" },
  { id: "Taiwan", value: "Taiwan" },
  { id: "Tajikistan", value: "Tajikistan" },
  { id: "Tanzania", value: "Tanzania" },
  { id: "Thailand", value: "Thailand" },
  { id: "Timor-Leste", value: "Timor-Leste" },
  { id: "Togo", value: "Togo" },
  { id: "Tonga", value: "Tonga" },
  { id: "Trinidad and Tobago", value: "Trinidad and Tobago" },
  { id: "Tunisia", value: "Tunisia" },
  { id: "Turkey", value: "Turkey" },
  { id: "Turkmenistan", value: "Turkmenistan" },
  { id: "Tuvalu", value: "Tuvalu" },
  { id: "Uganda", value: "Uganda" },
  { id: "Ukraine", value: "Ukraine" },
  { id: "United Arab Emirates", value: "United Arab Emirates" },
  { id: "United Kingdom", value: "United Kingdom" },
  { id: "United States of America", value: "United States of America" },
  { id: "Uruguay", value: "Uruguay" },
  { id: "Uzbekistan", value: "Uzbekistan" },
  { id: "Vanuatu", value: "Vanuatu" },
  { id: "Vatican City (Holy See)", value: "Vatican City (Holy See)" },
  { id: "Venezuela", value: "Venezuela" },
  { id: "Vietnam", value: "Vietnam" },
  { id: "Yemen", value: "Yemen" },
  { id: "Zambia", value: "Zambia" },
  { id: "Zimbabwe", value: "Zimbabwe" },
];

export const OTP_TIMER = 60 * 1;

export const ACCEPT_FILES = "image/*, application/pdf";
export const MAX_FILE_LIMIT = 7;
export const MAX_FILE_SIZE = 2 * 1024 * 1024;

// Fields we want to encrypt
export const SENSITIVE_FIELDS = [
  "otp",
  "password",
  "confirmPassword",
  "currentPassword",
  "newPassword",
];

export const RESPONSE_INTENTS = {
  OTP_SENT: "OTP_SENT",
  MULTIPLE_CHARGES: "MULTIPLE_CHARGES",
  SINGLE_CHARGE: "SINGLE_CHARGE",
};

export const HTTP_METHODS = {
  GET: "GET",
  POST: "POST",
  PUT: "PUT",
  DELETE: "DELETE",
  PATCH: "PATCH",
};

export const FLOW_CHART_IMAGE =
  "https://bucket-name-basic.s3.us-east-2.amazonaws.com/rabbies/complaints/dialog_2025-07-30T07-40-42.png";

export const COMPLAINT_QUERY_NAME = {
  new_complaints: "new_complaints",
  track_complaints: "track_complaints",
  resolved_complaints: "resolved_complaints",
  disposed_with_action_complaints: "disposed_with_action_complaints",
  disposed_without_action_complaints: "disposed_without_action_complaints",
  all_complaints: "all_complaints",
  inbox_complaints: "inbox_complaints",
  sent_complaints: "sent_complaints",
  complainant_complaints: "complainant_complaints",
};

export const forwardChargeSteps = [
  {
    title: "Select officers",
    description: "Choose designation, location and charges",
    icon: "1",
    id: 1,
  },
  {
    title: "Remarks & Attachment",
    description: "Add details and supporting documents",
    icon: "2",
    id: 2,
  },
  {
    title: "Review & Submit",
    description: "Confirm and submit your complaint",
    icon: "3",
    id: 3,
  },
];

export const FORWARD_COMPLAINT_STATUS = {
  NEW: "NEW",
  INBOX: "INBOX",
  SENT: "SENT",
};

export const COMPLAINT_STATUS = {
  INITIAL_APPLICATION: "INITIAL_APPLICATION",
  FURTHER_VERIFICATION: "FURTHER_VERIFICATION",
  FURTHER_DOCUMENTS_REQUIRED: "FURTHER_DOCUMENTS_REQUIRED",
  RESOLVED_WITH_ACTION: "RESOLVED_WITH_ACTION",
  RESOLVED_NO_ACTION: "RESOLVED_NO_ACTION",
  OPEN_INQUIRY: "OPEN_INQUIRY",
  FILE_NOT_RELAVENT: "FILE_NOT_RELAVENT",
  DISPOSED: "DISPOSED",
  FORWARDED_TO_ACE_COMMITEE: "Forwarded to ACE Commitee", // new added
  REFER_COMPLAINT: "REFER_COMPLAINT", // new added
};

export const USER_ROLES = {
  COMPLAINANT: "COMPLAINANT",
};

export const API_METHODS = {
  GET: "GET",
  POST: "POST",
  PUT: "PUT",
  DELETE: "DELETE",
  PATCH: "PATCH",
};

// export const STALE_TIME=5 * 60 * 1000
export const STALE_TIME = 0;

export const OTP_REQUEST_NOTIFICATION_TYPES = ["SMS", "EMAIL"];

export const LOCATION_MAPPER = {
  1: "DIVISION",
  2: "DISTRICT",
  3: "CITY",
};

export const HABITUAL_COMPLAINANT_TAGS = {
  SUSPECTED_HABITUAL_COMPLAINANT: "SUSPECTED_HABITUAL_COMPLAINANT",
  HABITUAL_COMPLAINANT: "HABITUAL_COMPLAINANT",
};

// For hashing
export const SALT_ROUNDS = 10;
