export { default as Dashboard } from './Dashboard'
export { default as LodgeComplaintPage } from './LodgeComplaint/LodgeComplaintPage'
export { default as TrackComplaintsPage } from './TrackComplaints/TrackComplaintsPage'
export { default as LoginPage } from './login/LoginPage'
export { default as SignUpPage } from './signUp/SignUpPage'
export { default as ChangePasswordPage } from './ChangePassword/ChangePasswordPage'
export { default as SettingsPage } from './Settings/SettingsPage'
export { default as EditProfilePage } from './EditProfile/EditProfilePage'
export { default as LogoutPage } from './logout/LogoutPage'
export { default as NewComplaintsPage } from './NewComplaints/NewComplaintsPage'
export { default as ChargeApprovalRequetsPage } from './ChargeApprovalsRequests/ChargeApprovalsRequestsPage'
export {default as UnauthorizedAccessPage} from './Unauthorized/UnauthorizedAccessPage'
export {default as ComplaintDetailsPage} from './ComplaintDetails/ComplaintDetailsPage'
export {default as HomePage} from './Home/HomePage'
export {default as AboutPage} from './About/AboutPage'
export {default as ContactUsPage} from './Contact/ContactUsPage'
export {default as NewlyForwardedPage} from './NewlyForwarded/NewlyForwardedPage'
export {default as ReportsGenerationPage} from './Reports/ReportsGenerationPage' 
export {default as NotFound} from './NotFound'


export { default as ForgotPasswordPage } from './ForgotPassowrd/ForgetPasswordPage'
export { default as InboxComplaintsPage } from './InboxComplaints/InboxComplaintsPage'
export { default as SentComplaintsPage } from './SentComplaints/SentComplaintsPage'
export { default as ResolvedComplaintsPage } from './ResolvedComplaints/ResolvedComplaintsPage'
export { default as DisposeWithActionComplaintsPage } from './DisposeWithAction/DisposeWithActionPage'
export { default as DisposeWithoutActionComplaintsPage } from './DisposeWithoutAction/DisposeWithoutActionPage'
export { default as AllComplaintsPage } from './AllComplaints/AllComplaintsPage'
export { default as NotificationsPage } from './Notification/NotificationPage'
export { default as ComplainerComplaintsPage } from './ComplaintsByUser/ComplaintsByUserPage'
export { default as ResolvedWithoutComplaintsPage } from './ResolvewithoutAction/ResolvedWithoutActionPage'
export { default as TutorialsPage } from './Tutorials/TutorialsPage'
export { default as TutorialPage } from './Tutorial/TutorialPage'
export { default as ManualPage } from './Manual/ManualPage'
export { default as LodgeOpenComplaintPage } from './OpenComplainant/OpenComplaintPage'

export { default as AdminUsersPage } from './admins/AdminsPage'
export { default as AdminProfileDetailsPage } from './admins/AdminProfileDetailsPage'
export { default as ComplainantsPage } from './complainants/ComplainantsPage'

export { default as MobileAppReleasePage } from './MobileApp/MobileAppReleasePage'

export { default as ReferComplaintsPage } from './DisposeWithoutAction/ReferComplaintsPage'


